name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker login
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ayfalmane19/react-test -f Dockerfile.dev .

      # 4️⃣ Run tests
      - name: Run tests
        run: docker run -e CI=true ayfalmane19/react-test npm test
      # 5️⃣ Generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # 6️⃣ Deploy to AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-west-3-273354657218
          region: eu-west-3
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

       
